---

version: '3'

services:
  app:
    build: .
    # command: bundle exec puma -C config/puma.rb
    command: bundle exec rails s
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./public:/app/public
    expose:
      - 3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres:
